<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.

$wgSitename         = "Từ điển công nghệ";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
$wgScriptPath       = "/mediawiki";
$wgArticlePath = "/$1";
$wgDisableOutputCompression = true;
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL

$wgEnableUserEmail  = false;

$wgEmergencyContact = "webmaster@vntelecom.org";
$wgPasswordSender = "webmaster@vntelecom.org";

## For a detailed description of the following switches see
## http://meta.wikimedia.org/Enotif and http://meta.wikimedia.org/Eauthent
## There are many more options for fine tuning available see
## /includes/DefaultSettings.php
## UPO means: this is also a user preference option
$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "vntelecom_tudien";
$wgDBuser           = "root";
$wgDBpassword       = "";
$wgDBport           = "3306";
$wgDBprefix         = "wiki_";

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = true;

$wgLocalInterwiki   = $wgSitename;

$wgLanguageCode = "vi";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = $_SERVER['HTTP_HOST'] == 'm.tudiencongnghe.net' ? 'mobile' : 'monobook';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "http://creativecommons.org/licenses/by-nc-nd/3.0/";
$wgRightsText = "Attribution-Noncommercial-No Derivative Works 3.0 ";
$wgRightsIcon = "http://i.creativecommons.org/l/by-nc-nd/3.0/88x31.png";
# $wgRightsCode = "by-nc-nd"; # Not yet used

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$configdate = gmdate( 'YmdHis', @filemtime( __FILE__ ) );
$wgCacheEpoch = max( $wgCacheEpoch, $configdate );

$wgLocaltimezone = 'Asia/Saigon';
$oldtz = getenv("TZ");
putenv("TZ=$wgLocaltimezone");
$wgLocalTZoffset = date("Z") / 60;
putenv("TZ=$oldtz");

# This snippet prevents editing from anonymous users
$wgGroupPermissions['*']['edit'] = false;

# Extra namespaces
$wgLogo = '/images/logo.png';

@include __DIR__ . '/../../conf/config.local.php';

require_once("extensions/InputBox/InputBox.php");
require_once("extensions/Cite/Cite.php");
require_once("extensions/tdcn/tdcn.php");

require_once("$IP/extensions/ParserFunctions/ParserFunctions.php");

require_once("$IP/extensions/Preloader/Preloader.php");
$wgPreloaderSource[NS_MAIN] = 'Template:Preload';
$wgShowExceptionDetails = true;
